### ISSUE TITLE
Many warnings during fingerprinting

### ISSUE THREAD

**Issue by vargenau** [scanoss/scanoss.py#12]
**Last week I ran the following with scanoss-py version 1.0.4**

svn checkout svn+ssh://svn.code.sf.net/p/phpwiki/code/trunk phpwiki

scanoss-py version
Version: 1.0.4

scanoss-py scan --format spdxlite --output phpwiki.spdx.json phpwiki/

Searching phpwiki/ for files to fingerprint...

Fingerprinting -

Scanning |################################| 1220/1220
Warning: Failed to find valid SPDX license identifier for: LicenseRef-scancode-unknown-license-reference
Warning: Failed to find valid SPDX license identifier for: LicenseRef-scancode-unknown-license-reference

**Today, I upgraded to scanoss-py version 1.0.6 and ran the same.**

scanoss-py scan --format spdxlite --output phpwiki.spdx.json phpwiki/

Writing results to phpwiki.spdx.json...
Searching phpwiki/ for files to fingerprint...
Fingerprinting /ERROR: The SCANOSS API returned an invalid JSON: Expecting ',' delimiter: line 2 column 1 (char 7220)
Ignoring result. Please look in "bad_json-139679631443520-1664286414.txt" for more details.
Fingerprinting -
Scanning |##########                      | 392/1220ERROR: The SCANOSS API returned an invalid JSON: Expecting ',' delimiter: line 2 column 1 (char 75176)
Ignoring result. Please look in "bad_json-139679606265408-1664286429.txt" for more details.
Scanning |####################            | 778/1220ERROR: The SCANOSS API returned an invalid JSON: Expecting ',' delimiter: line 2 column 1 (char 5462)
Ignoring result. Please look in "bad_json-139679614658112-1664286437.txt" for more details.
Scanning |########################        | 922/1220ERROR: The SCANOSS API returned an invalid JSON: Expecting ',' delimiter: line 2 column 1 (char 10184)
Ignoring result. Please look in "bad_json-139679089280576-1664286449.txt" for more details.
Scanning |############################    | 1095/1220ERROR: The SCANOSS API returned an invalid JSON: Expecting ',' delimiter: line 2 column 1 (char 11708)
Ignoring result. Please look in "bad_json-139679606265408-1664286451.txt" for more details.
Scanning |############################### | 1189/1220ERROR: The SCANOSS API returned an invalid JSON: Expecting ',' delimiter: line 2 column 1 (char 33099)
Ignoring result. Please look in "bad_json-139679623050816-1664286452.txt" for more details.
Scanning |################################| 1220/1220
Warning: Failed to find valid SPDX license identifier for: LicenseRef-scancode-unknown-license-reference
Warning: Failed to find valid SPDX license identifier for: LicenseRef-scancode-unknown-license-reference

**Now I have many warnings.**

**Comment by mscasso-scanoss** [comment]
Dear @vargenau ,
The problem you were experiencing was related with bug in our scanning engine. It was solved and updated today. I have scanned successfully the repository you mentioned. Sorry for the inconvenience, please give a new try.

**Comment by vargenau** [comment]
I confirm the issue is solved.
Thank you very much for your quick fix.
You can close the ticket.

**Comment by eeisegn** [comment]
Hi,

We will investigate the SPDX license output and attempt to fix this issue.

Thanks!

**Comment by vargenau** [comment]
Yes, it works now. You can close the ticket after releasing 1.0.7.

Thank you for your quick fix.

**Comment by eeisegn** [comment]
These changes have now been published in [PyPI](https://pypi.org/project/scanoss/1.1.0/) and [GHCR](https://github.com/scanoss/scanoss.py/pkgs/container/scanoss-py).
