### ISSUE TITLE
Regression in PURL syntax between SCANOSS 1.0.4 and 1.0.6

### ISSUE THREAD

**Issue by vargenau** [scanoss/scanoss.py#15]
```
svn checkout svn+ssh://svn.code.sf.net/p/phpwiki/code/trunk phpwiki

scanoss-py scan --format spdxlite --output phpwiki.spdx.json phpwiki/
```
Attached is result of the scan done last week with SCANOSS 1.0.4 and today with 1.0.6.

In 1.0.4 you get  ```"referenceLocator": "pkg:github/pbalan/mariadb@1.0.0"```

In 1.0.6 you get  ```"referenceLocator": "pkg:github/pbalan/mariadb@1.0.0@1.0.0"```

The 1.0.6 result does not seem to be a valid PURL.

[phpwiki-with-scanoss1.0.4.spdx.json.txt](https://github.com/scanoss/scanoss.py/files/9663336/phpwiki-with-scanoss1.0.4.spdx.json.txt)
[phpwiki-with-scanoss1.0.6.spdx.json.txt](https://github.com/scanoss/scanoss.py/files/9663334/phpwiki-with-scanoss1.0.6.spdx.json.txt)

**Comment by mscasso-scanoss** [comment]
Hi again @vargenau. Thank you one more time for report this issue, like the other one you had reported, it was related with an update in our scanning engine. The bug was solved, please give a new try.

**Comment by vargenau** [comment]
I confirm it works now.

You can close the ticket.
