### ISSUE TITLE
Cannot parse wfp files for C++ projects?

### ISSUE THREAD

**Issue by sebastianpfischer** [scanoss/scanoss.py#18]
After setting up a 3.9.13 env, `poetry run scanoss-py scan -o scan-output.json .` works but when I call `poetry run python -m scanoss.cli scanner_output.wfp`, I get:
`
usage: cli.py [-h] {version,ver,scan,sc,fingerprint,fp,wfp,dependencies,dp,dep} ...
cli.py: error: argument subparser: invalid choice: 'scanner_output.wfp' (choose from 'version', 'ver', 'scan', 'sc', 'fingerprint', 'fp', 'wfp', 'dependencies', 'dp', 'dep')
`

**Comment by eeisegn** [comment]
Hi Sebastian,

You are missing the "action" command from the second command. I should be one of `scan, wfp, dep`.
So your command should look something like these:

`poetry run python -m scanoss.cli scan -o scan-output.json .`
`poetry run python -m scanoss.cli wfp -o fingers.wfp .`
`poetry run python -m scanoss.cli scan -o scan-output.json -w fingers.wfp`

Make sense or did we misunderstand your intent?

Thanks!

**Comment by sebastianpfischer** [comment]
Hi @eeisegn,

sorry, my bad, somehow I got confused by the https://github.com/scanoss/scanoss.py/blob/main/PACKAGE.md...
I miss read that `scanoss.cli` is the same as `scanoss-py`.

**Comment by sebastianpfischer** [comment]
Else, do you support .spdx files with the cli?

**Comment by eeisegn** [comment]
Hi,

We support exporting results in the following formats:
- RAW (json)
- SPDX Lite (json)
- CycloneDX (json)
- CSV

Or `scanoss-js` [client](https://www.npmjs.com/package/scanoss) also supports HTML report generation. If you want to review the results graphically, please look at our [Audit Workbench](https://scanoss.com/product).

Thanks!
