### ISSUE TITLE
Large repository scans will continue to be attempted(Retrying...) without an exit mechanism 

### ISSUE THREAD

**Issue by fengchen-boot** [scanoss/scanoss.py#19]
We scan this repository(https://gitee.com/openeuler/bishengjdk-8)  
**scanoss-py scan --key mykey --apiurl https://mydomain.com/api/scan/direct --wfp /root/scanoss/wfp/scanoss-version--91--1.wfp --output /root/scanoss/json/bishengjdk-8-202305181429100.json**
**use scanoss command convert wfp to json  ,The scanning results are as follows:**
Scanning |##                              | 2716/42334No response object returned from API. Please look in "bad_request-140081012659968-0893cc28-ee0f-4350-90c0-9672a8aa7625.txt" for the offending WFP.
Warning: Error response code 504 (...

[Additional comments moved to official support channel by SCANOSS]

**Large repository scanning will continue to retry without an exit mechanism** 

**Expected results
We need to return the script error code if there are any abnormalities in the scan, instead of constantly trying again**

**Comment by scanoss-cs** [comment]
Working on a command option to allow you to configure how quickly a scan should fail.

**Comment by scanoss-cs** [comment]
Hi,

A new version of `scanoss-py` has been released [v1.5.2](https://github.com/scanoss/scanoss.py/releases/tag/v1.5.2) which has support for a `--retry` command option to alter the default retry of 5 to a number that best suits your needs.
You can install it using:

`pip3 install --upgrade scanoss`

Thanks! SCANOSS
