### ISSUE TITLE
SPDX Support?

### ISSUE THREAD

**Issue by maxhbr** [scanoss/scanoss.py#4]
Does this application support generation of SPDX?

The other clients, that mentioned spdx supported, [scanner.py](https://github.com/scanoss/scanner.py) and [scanner.c](https://github.com/scanoss/scanner.c), are deprecated.

I do not yet find any hints for SPDX document export support in this client. Is that present / planned?

**Comment by mscasso-scanoss** [comment]
Dear @maxhbr , we plan to release a new version of scanoss.py  in December adding the spdx output. Are you agree? is this enough for you?

**Comment by scanoss-cs** [comment]
Hi @maxhbr ,

We have just released a version of [scanoss.py](https://pypi.org/project/scanoss/) with supports SPDX Lite as an output format option:

`scanoss-py scan --format spdxlite --output results-spdxlite.json <folder>`

Can you please check if this satisfies your need?

Thanks!

**Comment by maxhbr** [comment]
Is there a way to generate multiple outputs types at the same time, without rescanning?

**Comment by maxhbr** [comment]
I did an example scan and got:
```
{
  "spdxVersion": "SPDX-2.2",
  "dataLicense": "CC0-1.0",
  "SPDXIdentifier": "SCANOSS-SPDX-615ab4429f7a6404db0e61f7d68bfe05",
  "DocumentName": "SCANOSS-SBOM",
  "creator": "Tool: SCANOSS-PY",
  "created": "2021-12-11T15:13:46.003Z",
  "Packages": [
    {
      "PackageName": "serve",
      "PackageSPDXID": "pkg:github/fkautz/serve",
      "PackageVersion": "1.0.0",
      "PackageDownloadLocation": "https://github.com/fkautz/serve",
      "DeclaredLicense": "(Apache-2.0)"
    }
  ]
}
```
The output validates against the v2.2 schema:
```
$ jsonschema -i scanoss.spdxlite.json  <(curl https://raw.githubusercontent.com/spdx/spdx-spec/v2.2/schemas/spdx-schema.json)
$ echo $?
0
```

### but it does not validate against `v2.2.1` which should effectively be equivalent to `v2.2`:

```
$ jsonschema -i scanoss.spdxlite.json  <(curl https://raw.githubusercontent.com/spdx/spdx-spec/v2.2.1/schemas/spdx-schema.json)
{'spdxVersion': 'SPDX-2.2', 'dataLicense': 'CC0-1.0', 'SPDXIdentifier': 'SCANOSS-SPDX-615ab4429f7a6404db0e61f7d68bfe05', 'DocumentName': 'SCANOSS-SBOM', 'creator': 'Tool: SCANOSS-PY', 'created': '2021-12-11T15:13:46.003Z', 'Packages': [{'PackageName': 'serve', 'PackageSPDXID': 'pkg:github/fkautz/serve', 'PackageVersion': '1.0.0', 'PackageDownloadLocation': 'https://github.com/fkautz/serve', 'DeclaredLicense': '(Apache-2.0)'}]}: 'SPDXID' is a required property
{'spdxVersion': 'SPDX-2.2', 'dataLicense': 'CC0-1.0', 'SPDXIdentifier': 'SCANOSS-SPDX-615ab4429f7a6404db0e61f7d68bfe05', 'DocumentName': 'SCANOSS-SBOM', 'creator': 'Tool: SCANOSS-PY', 'created': '2021-12-11T15:13:46.003Z', 'Packages': [{'PackageName': 'serve', 'PackageSPDXID': 'pkg:github/fkautz/serve', 'PackageVersion': '1.0.0', 'PackageDownloadLocation': 'https://github.com/fkautz/serve', 'DeclaredLicense': '(Apache-2.0)'}]}: 'name' is a required property
{'spdxVersion': 'SPDX-2.2', 'dataLicense': 'CC0-1.0', 'SPDXIdentifier': 'SCANOSS-SPDX-615ab4429f7a6404db0e61f7d68bfe05', 'DocumentName': 'SCANOSS-SBOM', 'creator': 'Tool: SCANOSS-PY', 'created': '2021-12-11T15:13:46.003Z', 'Packages': [{'PackageName': 'serve', 'PackageSPDXID': 'pkg:github/fkautz/serve', 'PackageVersion': '1.0.0', 'PackageDownloadLocation': 'https://github.com/fkautz/serve', 'DeclaredLicense': '(Apache-2.0)'}]}: 'creationInfo' is a required property
{'spdxVersion': 'SPDX-2.2', 'dataLicense': 'CC0-1.0', 'SPDXIdentifier': 'SCANOSS-SPDX-615ab4429f7a6404db0e61f7d68bfe05', 'DocumentName': 'SCANOSS-SBOM', 'creator': 'Tool: SCANOSS-PY', 'created': '2021-12-11T15:13:46.003Z', 'Packages': [{'PackageName': 'serve', 'PackageSPDXID': 'pkg:github/fkautz/serve', 'PackageVersion': '1.0.0', 'PackageDownloadLocation': 'https://github.com/fkautz/serve', 'DeclaredLicense': '(Apache-2.0)'}]}: Additional properties are not allowed ('creator', 'created', 'SPDXIdentifier', 'Packages', 'DocumentName' were unexpected)
```
I think that should be fixed (the https://github.com/spdx/spdx-spec/blob/development/v2.2.2/examples/SPDXJSONExample-v2.2.spdx.json for example validates against v2.2 AND v2.2.1)

### Although I think it is not yet fully compliant:
* the `filesAnalyzed` property is not required, but the default value of `true` is assumed (see https://spdx.github.io/spdx-spec/package-information/#78-files-analyzed-field), with that a lot more fields are required to be compliant.
  * spdxlite wants you to set it to `false` (https://spdx.github.io/spdx-spec/SPDX-Lite/)
* the `PackageDownloadLocation` should be of a very specific format (for git) or should directly point to the .tar.gz (see https://spdx.github.io/spdx-spec/package-information/#771-description)
  * maybe https://spdx.github.io/spdx-spec/package-information/#711-package-home-page-field would match better
* the PackageSPDXID shall be of the format `"SPDXRef-"[idstring]`  where `[idstring]` is a unique string containing letters, numbers, `.`, and/or `-`. (see https://spdx.github.io/spdx-spec/package-information/#72-package-spdx-identifier-field). It is not allowed to contain `:` or `/`. The PURL should probably be placed in https://spdx.github.io/spdx-spec/package-information/#721-external-reference-field

I hope that feedback will help.

**Comment by scanoss-cs** [comment]
> Is there a way to generate multiple outputs types at the same time, without rescanning?

There isn't, but we'll add it to the backlog to provide it.

**Comment by maxhbr** [comment]
> There isn't, but we'll add it to the backlog to provide it.

Great, thank you. I think that will be helpful.

**Comment by scanoss-cs** [comment]
> I did an example scan and got:
> 
> ```
> {
>   "spdxVersion": "SPDX-2.2",
>   "dataLicense": "CC0-1.0",
>   "SPDXIdentifier": "SCANOSS-SPDX-615ab4429f7a6404db0e61f7d68bfe05",
>   "DocumentName": "SCANOSS-SBOM",
>   "creator": "Tool: SCANOSS-PY",
>   "created": "2021-12-11T15:13:46.003Z",
>   "Packages": [
>     {
>       "PackageName": "serve",
>       "PackageSPDXID": "pkg:github/fkautz/serve",
>       "PackageVersion": "1.0.0",
>       "PackageDownloadLocation": "https://github.com/fkautz/serve",
>       "DeclaredLicense": "(Apache-2.0)"
>     }
>   ]
> }
> ```
> 
> The output validates against the v2.2 schema:
> 
> ```
> $ jsonschema -i scanoss.spdxlite.json  <(curl https://raw.githubusercontent.com/spdx/spdx-spec/v2.2/schemas/spdx-schema.json)
> $ echo $?
> 0
> ```
> 
> ### but it does not validate against `v2.2.1` which should effectively be equivalent to `v2.2`:
> ```
> $ jsonschema -i scanoss.spdxlite.json  <(curl https://raw.githubusercontent.com/spdx/spdx-spec/v2.2.1/schemas/spdx-schema.json)
> {'spdxVersion': 'SPDX-2.2', 'dataLicense': 'CC0-1.0', 'SPDXIdentifier': 'SCANOSS-SPDX-615ab4429f7a6404db0e61f7d68bfe05', 'DocumentName': 'SCANOSS-SBOM', 'creator': 'Tool: SCANOSS-PY', 'created': '2021-12-11T15:13:46.003Z', 'Packages': [{'PackageName': 'serve', 'PackageSPDXID': 'pkg:github/fkautz/serve', 'PackageVersion': '1.0.0', 'PackageDownloadLocation': 'https://github.com/fkautz/serve', 'DeclaredLicense': '(Apache-2.0)'}]}: 'SPDXID' is a required property
> {'spdxVersion': 'SPDX-2.2', 'dataLicense': 'CC0-1.0', 'SPDXIdentifier': 'SCANOSS-SPDX-615ab4429f7a6404db0e61f7d68bfe05', 'DocumentName': 'SCANOSS-SBOM', 'creator': 'Tool: SCANOSS-PY', 'created': '2021-12-11T15:13:46.003Z', 'Packages': [{'PackageName': 'serve', 'PackageSPDXID': 'pkg:github/fkautz/serve', 'PackageVersion': '1.0.0', 'PackageDownloadLocation': 'https://github.com/fkautz/serve', 'DeclaredLicense': '(Apache-2.0)'}]}: 'name' is a required property
> {'spdxVersion': 'SPDX-2.2', 'dataLicense': 'CC0-1.0', 'SPDXIdentifier': 'SCANOSS-SPDX-615ab4429f7a6404db0e61f7d68bfe05', 'DocumentName': 'SCANOSS-SBOM', 'creator': 'Tool: SCANOSS-PY', 'created': '2021-12-11T15:13:46.003Z', 'Packages': [{'PackageName': 'serve', 'PackageSPDXID': 'pkg:github/fkautz/serve', 'PackageVersion': '1.0.0', 'PackageDownloadLocation': 'https://github.com/fkautz/serve', 'DeclaredLicense': '(Apache-2.0)'}]}: 'creationInfo' is a required property
> {'spdxVersion': 'SPDX-2.2', 'dataLicense': 'CC0-1.0', 'SPDXIdentifier': 'SCANOSS-SPDX-615ab4429f7a6404db0e61f7d68bfe05', 'DocumentName': 'SCANOSS-SBOM', 'creator': 'Tool: SCANOSS-PY', 'created': '2021-12-11T15:13:46.003Z', 'Packages': [{'PackageName': 'serve', 'PackageSPDXID': 'pkg:github/fkautz/serve', 'PackageVersion': '1.0.0', 'PackageDownloadLocation': 'https://github.com/fkautz/serve', 'DeclaredLicense': '(Apache-2.0)'}]}: Additional properties are not allowed ('creator', 'created', 'SPDXIdentifier', 'Packages', 'DocumentName' were unexpected)
> ```
> 
> I think that should be fixed (the https://github.com/spdx/spdx-spec/blob/development/v2.2.2/examples/SPDXJSONExample-v2.2.spdx.json for example validates against v2.2 AND v2.2.1)
> 
> ### Although I think it is not yet fully compliant:
> * the `filesAnalyzed` property is not required, but the default value of `true` is assumed (see https://spdx.github.io/spdx-spec/package-information/#78-files-analyzed-field), with that a lot more fields are required to be compliant.
>   
>   * spdxlite wants you to set it to `false` (https://spdx.github.io/spdx-spec/SPDX-Lite/)
> * the `PackageDownloadLocation` should be of a very specific format (for git) or should directly point to the .tar.gz (see https://spdx.github.io/spdx-spec/package-information/#771-description)
>   
>   * maybe https://spdx.github.io/spdx-spec/package-information/#711-package-home-page-field would match better
> * the PackageSPDXID shall be of the format `"SPDXRef-"[idstring]`  where `[idstring]` is a unique string containing letters, numbers, `.`, and/or `-`. (see https://spdx.github.io/spdx-spec/package-information/#72-package-spdx-identifier-field). It is not allowed to contain `:` or `/`. The PURL should probably be placed in https://spdx.github.io/spdx-spec/package-information/#721-external-reference-field
> 
> I hope that feedback will help.

Perfect! Thank you for this feedback!
We will review this output and make any necessary changes.

**Comment by scanoss-cs** [comment]
Hi Max,

We have done some testing against these schemas and made the following change:

`{
  "spdxVersion": "SPDX-2.2",
  "dataLicense": "CC0-1.0",
  "SPDXID": "SPDXRef-8e4cca241facba54781980e11167e474",
  "name": "SCANOSS-SBOM",
  "creationInfo": {
    "created": "2021-12-13T17:22:06.778Z",
    "creators": [
      "Tool: SCANOSS-PY: 0.7.3",
      "User: SCANOSS"
    ]
  },
  "packages": [
    {
      "name": "scanoss.py",
      "SPDXID": "pkg:github/scanoss/scanoss.py",
      "versionInfo": "0.7.0",
      "downloadLocation": "",
      "homepage": "https://github.com/scanoss/scanoss.py",
      "licenseDeclared": "(MIT AND GPL-2.0-only AND GPL 2.0 or later)",
      "licenseConcluded": "",
      "filesAnalyzed": false,
      "copyrightText": ""
    }
  ]
}
`

We had to add the "licenseConcluded", "copyrightText" fields to get the validation to pass.
For the Lite version, we're not including the copyright text, and we will include the actual "downloadLocation" in a future release (the field needs to be returned as part of the scan result).

**Comment by scanoss-cs** [comment]
Does this make sense?

**Comment by maxhbr** [comment]
I reformatted your new output:
```
{
    "spdxVersion": "SPDX-2.2",
     "dataLicense": "CC0-1.0",
     "SPDXID": "SPDXRef-8e4cca241facba54781980e11167e474",
     "name": "SCANOSS-SBOM",
     "creationInfo": { "created": "2021-12-13T17:22:06.778Z", "creators": [ "Tool: SCANOSS-PY: 0.7.3", "User: SCANOSS" ] },
     "packages": [ 
         {
             "name": "scanoss.py",
             "SPDXID": "pkg:github/scanoss/scanoss.py",
             "versionInfo": "0.7.0",
             "downloadLocation": "",
             "homepage": "https://github.com/scanoss/scanoss.py",
             "licenseDeclared": "(MIT AND GPL-2.0-only AND GPL 2.0 or later)",
             "licenseConcluded": "",
             "filesAnalyzed": false,
             "copyrightText": "" 
         }
     ]
} 
```

### some comments
- Instead off `""` it should probably use `NOASSERTION` (meaning "the SPDX document creator has made no attempt to determine this field") (or `NONE`).
- the `licenseDeclared` is not valid SPDX license expression, since the last name is not a valid license ID
- the SPDXID of the package does not match the expected format (see above)
- I think the licenseListVersion is a required field if I read https://spdx.github.io/spdx-spec/document-creation-information/#67-license-list-version-field correctly
- minor: I think in the very strict interpretation, `SCANOSS` is not a person and can not be used as a creating user

**Comment by scanoss-cs** [comment]
OK.

- `NOASSERTION` has been added.
- For `licenseDeclared` we're trying to keep the SPDX Lite format simple. We can see examples with that format of text being used?
- Similarly, for `SPDXID` we're trying to keep it simple. Do you believe, even for SPDX Lite, we should be recording it as a complex object?
- We put in the username that generated the report. I just changed it to SCANOSS for sharing.

**Comment by scanoss-cs** [comment]
`{
  "spdxVersion": "SPDX-2.2",
  "dataLicense": "CC0-1.0",
  "SPDXID": "SPDXRef-82fc52304a0cce93322d7f9919a8b2df",
  "name": "SCANOSS-SBOM",
  "creationInfo": {
    "created": "2021-12-13T19:56:51.592Z",
    "creators": [
      "Tool: SCANOSS-PY: 0.7.3",
      "User: egans"
    ]
  },
  "packages": [
    {
      "name": "scanoss.py",
      "SPDXID": "pkg:github/scanoss/scanoss.py",
      "versionInfo": "0.7.0",
      "downloadLocation": "https://github.com/scanoss/scanoss.py",
      "homepage": "https://github.com/scanoss/scanoss.py",
      "licenseDeclared": "(MIT AND GPL-2.0-only AND GPL 2.0 or later)",
      "licenseConcluded": "NOASSERTION",
      "filesAnalyzed": false,
      "copyrightText": "NOASSERTION"
    }
  ]
}`

**Comment by maxhbr** [comment]
* the `SPDXID` just disallows `:` and `/` in the string, and has a specific format. So that might break for parsers that expect that format.
  >  `"SPDXRef-"[idstring]`  where `[idstring]` is a unique string containing letters, numbers, `.`, and/or `-`.



> For licenseDeclared we're trying to keep the SPDX Lite format simple. We can see examples with that format of text being used?

* The problem is that `GPL 2.0 or later` is not a valid SPDX ID, it should be `GPL-2.0-or-later`. The names must come from https://spdx.org/licenses/ or need to be prefixed with `LicenseRef-`, whitespace is forbidden in any case

**Comment by scanoss-cs** [comment]
Understood! Will look into both of those.

Thanks!

**Comment by scanoss-cs** [comment]
Hi Max,

We've iterated a little more. Does this look better?

```
{
  "spdxVersion": "SPDX-2.2",
  "dataLicense": "CC0-1.0",
  "SPDXID": "SPDXRef-3b9afc9693391e58bfb78054c24524e5",
  "name": "SCANOSS-SBOM",
  "creationInfo": {
    "created": "2021-12-14T16:01:29.875Z",
    "creators": [
      "Tool: SCANOSS-PY: 0.7.4",
      "User: egans"
    ]
  },
  "packages": [
    {
      "name": "scanoss.py",
      "SPDXID": "SPDXRef-scanoss.py-1b244c08278edc8b33810f1025b03f7a",
      "versionInfo": "0.7.0",
      "downloadLocation": "https://github.com/scanoss/scanoss.py",
      "homepage": "https://github.com/scanoss/scanoss.py",
      "licenseDeclared": "(MIT AND GPL-2.0-only AND GPL-2.0-or-later)",
      "licenseConcluded": "NOASSERTION",
      "filesAnalyzed": false,
      "copyrightText": "NOASSERTION",
      "externalRefs": [
        {
          "referenceCategory": "PACKAGE_MANAGER",
          "referenceLocator": "pkg:github/scanoss/scanoss.py@0.7.0",
          "referenceType": "purl"
        }
      ]
    }
 ]
}
```

**Comment by maxhbr** [comment]
Looks good, but I will need to validate it at some point with a bigger example
