### ISSUE TITLE
Module pkg_resources deprecated on Python 3.12 but it used in line 28(scanner.py)

### ISSUE THREAD

**Issue by userai-dev** [scanoss/scanoss.py#42]
This is standard environment of Ubuntu 24-it uses Python 3.12 installed by default.

Module pkg_resources deprecated on Python 3.12 but it used in line 28(scanner.py) cannot install scanoss even using pipx recommended workflow.
scanoss 1.13.0

qa@qa-VirtualBox:~/Desktop$ pipx install scanoss
  installed package scanoss 1.13.0, installed using Python 3.12.3
  These apps are now globally available
    - scanoss-py
done! ✨ 🌟 ✨

qa@qa-VirtualBox:~/Desktop$ scanoss-py
Traceback (most recent call last):
  File "/home/qa/.local/bin/scanoss-py", line 5, in <module>
    from scanoss.cli import main
  File "/home/qa/.local/share/pipx/venvs/scanoss/lib/python3.12/site-packages/scanoss/cli.py", line 30, in <module>
    from .scanner import Scanner
  File "/home/qa/.local/share/pipx/venvs/scanoss/lib/python3.12/site-packages/scanoss/scanner.py", line 28, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'

qa@qa-VirtualBox:~/Desktop$ python3
Python 3.12.3 (main, Apr 10 2024, 05:33:47) [GCC 13.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pkg_resources
<stdin>:1: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
>>>

**Comment by eeisegn** [comment]
Hi,

The `scanoss-py` package has not been tested/upgraded to work with Python 3.12 just yet. It is on the TODO list.

In the interim, we suggest you proceed with Python 3.11, or if you cannot, feel free to submit a PR for a proposed fix?

Thanks!

**Comment by scanossjeronimo** [comment]
This issue was solved in #44 and will be added in v1.14.0.

Closing this issue.
