### ISSUE TITLE
the cli tool sends post requests that exceed the limit by 1 (Warning: Post size 65537 greater than limit 65536)

### ISSUE THREAD

**Issue by maxhbr** [scanoss/scanoss.py#5]
When calling `scanoss-py fingerprint ...` and afterwards `scanoss-py scan ...` I get the following warnings:
```
$ scanoss-py scan [...]
[...]
Warning: Post size 65537 greater than limit 65536
Warning: Post size 65537 greater than limit 65536
[...]
$ scanoss-py version
Version: 0.7.4
```
installed via pip

**Comment by maxhbr** [comment]
It still produces output, but I do not know if that is complete.

**Comment by eeisegn** [comment]
Hi Max!

This is just a warning that the WFP for a file is larger than 64k.
We find that some organisations limit the POST size on a HTTP request via a proxy/firewall.
We try to limit the size of a post to this 64k limit, but if a single WFP is larger than 64k, we simply warn you and attempt to post it regardless.

Make sense?

Thanks!

**Comment by maxhbr** [comment]
Ah, makes sense, I just though it might we worth reporting it. For me it looked like an accidental trailing character that brought the post size over the limit. Thank you for clarification.
