### ISSUE TITLE
Invalid SPDX: date format

### ISSUE THREAD

**Issue by vargenau** [scanoss/scanoss.py#61]
[phpwiki.json](https://github.com/user-attachments/files/17437004/phpwiki.json)

```
pyspdxtools -i phpwiki.json 
ERROR:root:There have been issues while parsing the provided document:
Error while parsing Document: ["time data '2024-10-18T14:30:40.702Z' does not match format '%Y-%m-%dT%H:%M:%SZ'"]
```

**Comment by ortizjeronimo** [comment]
Hello @vargenau, we've raised a pull request (#64) to correct this.

Thanks for the observation!

**Comment by ortizjeronimo** [comment]
@vargenau PR #64 has been merged!
This issue will be closed.
