### ISSUE TITLE
post_processor is used without initialization

### ISSUE THREAD

**Issue by JustinWonjaePark** [scanoss/scanoss.py#79]
In scanner.py, the post_processor attribute is not initialized when scan_settings is not provided as a parameter in the __init__ method. ([Reference](https://github.com/scanoss/scanoss.py/blob/51ac647d4ca01cfad437109870c86bf935f74ddd/src/scanoss/scanner.py#L166))

However, it is still being accessed in the __finish_scan_threaded method. ([Reference](https://github.com/scanoss/scanoss.py/blob/51ac647d4ca01cfad437109870c86bf935f74ddd/src/scanoss/scanner.py#L528))

This can cause an AttributeError if scan_settings is not provided during the instantiation of the Scanner class.

**Comment by matiasdaloia** [comment]
Hi @JustinWonjaePark thanks for pointing out! This is going to be fixed on [this](https://github.com/scanoss/scanoss.py/pull/76/commits/9fd0502c2110a1cff037863aafdc7adc3a253008#diff-54daea2ce27c020f5383bdfa0a0edc378f14f2990b693211ec652e38dcdf5094R527) commit
